---
- name: download restic
  ansible.builtin.get_url:
    url: 'https://github.com/restic/restic/releases/download/v{{ restic_restic_version }}/restic_{{ restic_restic_version }}_linux_{{ restic_architecture_map[ansible_architecture] }}.bz2'
    checksum: 'sha256sum:https://github.com/restic/restic/releases/download/v{{ restic_restic_version }}/SHA256SUMS'
    dest: /usr/local/src/restic.bz2
  register: download_restic
  when: not ansible_check_mode

- name: extract restic
  ansible.builtin.unarchive:
    src: /usr/local/src/restic.bz2
    dest: /usr/local/bin/restic
    remote_src: true
    include: 'restic_*'
  when:
    - download_restic is changed
    - not ansible_check_mode

- name: download rclone
  ansible.builtin.get_url:
    url: 'https://github.com/rclone/rclone/releases/download/{{ restic_rclone_version }}/rclone-{{ restic_rclone_version }}-linux-{{ restic_architecture_map[ansible_architecture] }}.zip'
    checksum: 'sha256sum:https://github.com/rclone/rclone/releases/download/{{ restic_rclone_version }}/SHA256SUMS'
    dest: /usr/local/src/rclone.zip
  register: download_rclone
  when: not ansible_check_mode

- name: extract rclone
  ansible.builtin.unarchive:
    src: /usr/local/src/rclone.zip
    dest: /usr/local/bin/rclone
    remote_src: true
    include: 'rclone'
  when:
    - download_rclone is changed
    - not ansible_check_mode




