# -*- mode: ruby -*-
# vi: set ft=ruby :

CURRENT_PATH = File.dirname(File.expand_path(__FILE__))

Vagrant.configure("2") do |config|
  boxes = [
    { :name => "alma9", :box => "almalinux/9" },
    { :name => "bookworm", :box => "debian/bookworm64" },
    { :name => "buster", :box => "debian/buster64" },
    { :name => "jammy", :box => "ubuntu/jammy64" },
  ]

  last_octet = 10
  boxes.each do |opts|
    config.vm.define opts[:name] do |config|
      config.vm.box = opts[:box]
      config.vm.network "private_network", ip: "192.168.56.#{last_octet}"
      last_octet += 1
      config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 2
        vb.linked_clone = true  # Use if you create a lot of Vagrant VMs

        # # Workaround for Ubuntu Cloud init VMs (focal). Not needed any more in 2023.
        # # Create virtual serial port, output to file console-output.OS.
        # # Keep workaround in case Ubuntu foules up again.
        # vb.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
        # vb.customize ["modifyvm", :id, "--uartmode1", "file", "#{CURRENT_PATH}/console-output.#{opts[:name]}"]
      end
      if opts[:name] == boxes.last[:name]
        config.vm.provision "ansible: check",  type: "ansible", run: "always" do |ansible|
          ansible.compatibility_mode = "2.0"
          ansible.playbook = "test.yml"
          ansible.limit = "all"
          ansible.raw_arguments = ["--check", "--diff"]
          host_vars = {}
          last_octet = 10
          boxes.each do |opts|
            host_vars.store("#{opts[:name]}", {"ansible_host" => "192.168.56.#{last_octet}",
                                               "ansible_port" => 22})
            last_octet += 1
          end
          ansible.host_vars = host_vars
        end
        config.vm.provision "ansible: run", type: "ansible" do |ansible|
          ansible.compatibility_mode = "2.0"
          ansible.playbook = "test.yml"
          ansible.limit = "all"
          host_vars = {}
          last_octet = 10
          boxes.each do |opts|
            host_vars.store("#{opts[:name]}", {"ansible_host" => "192.168.56.#{last_octet}",
                                               "ansible_port" => 22})
            last_octet += 1
          end
          ansible.host_vars = host_vars
        end
      end
    end
  end
end

